### ISSUE TITLE
mysql.client require {{ mysql.server }} package which is not needed on debian

### ISSUE THREAD

**Issue by Sylvain303** [saltstack-formulas/mysql-formula#123]
part of `mysql/config.sls` included by `mysql/client.sls`, from [here](https://github.com/saltstack-formulas/mysql-formula/blob/master/mysql/config.sls#L57)

``` yaml
mysql_config:
  file.managed:
    - name: {{ mysql.config.file }}
    - require:
      - pkg: {{ mysql.server }}
    - template: jinja
{% if "config_directory" in mysql %}
    - source: salt://mysql/files/my-include.cnf
{% else %}
    - source: salt://mysql/files/my.cnf
{% endif %}
    {% if os_family in ['Debian', 'Gentoo', 'RedHat'] %}
    - user: root
    - group: root
    - mode: 644
    {% endif %}
```

If I just want to install the client on a webserver, to probe mysql connection from the webserver to the dbserver, I don't need to have the server package to be installed.

On Debian jessie there'are, 2 packages available:

mariadb-common

```
dpkg -L mariadb-common
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/mariadb-common
/usr/share/doc/mariadb-common/copyright
/usr/share/doc/mariadb-common/changelog.Debian.gz
/etc
/etc/mysql
/etc/mysql/conf.d
/etc/mysql/conf.d/mariadb.cnf
```

mysql-common

```
root@web0:~# dpkg -L mysql-common
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/mysql-common
/usr/share/doc/mysql-common/NEWS.Debian.gz
/usr/share/doc/mysql-common/changelog.gz
/usr/share/doc/mysql-common/copyright
/usr/share/doc/mysql-common/changelog.Debian.gz
/etc
/etc/mysql
/etc/mysql/my.cnf
/etc/mysql/conf.d
/etc/mysql/conf.d/.keepme
```
