### ISSUE TITLE
one user, two hosts grants

### ISSUE THREAD

**Issue by johnnyrun** [saltstack-formulas/mysql-formula#126]
Hi!
My mysql user "foo" can connect from localhost and from another ip. Same username, different ip.

At the moment I can't produce two entries in mysql.user table  with the same "User" field and different "Host" field

**Comment by johnnyrun** [comment]
ahhh ok...It is supported using "hosts", instead of "host"

```
mysql:
    user:                                                                                                  
      db_prod:                                                                                   
        password: 'dGd5ukkB'                                                                   
!       hosts:                                                                                            
         - 'localhost'                                                                                    
         - '172.16.115.25%'                                                                               
        databases:                                                                                         
          - database: 'db_prod'                                                                       
            grants: ['all']   
```
