### ISSUE TITLE
User grant fails to execute

### ISSUE THREAD

**Issue by robruma** [saltstack-formulas/mysql-formula#131]
Since 04c8db5fc0324fe903cdc6a4ac86e4ff9171693c I'm seeing the following error while using this formula to build MariaDB on CentOS 7. The user grant appears to fail while applying a minion highstate but running the command manually works fine.

```
----------
          ID: mysql_user_user_localhost_0
    Function: mysql_grants.present
        Name: admin_database_all
      Result: False
     Comment: Failed to execute: "GRANT all privileges ON database.* TO user@localhost" (MySQL Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1)
     Started: 23:11:53.928118
    Duration: 5.062 ms
     Changes:   
```

```
# mysql -psecret
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 127
Server version: 5.5.50-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use database
Database changed
MariaDB [database]> GRANT all privileges ON database.* TO user@localhost;
Query OK, 0 rows affected (0.03 sec)

MariaDB [database]>
```

Pillar data:
```
mysql:
  server:
    root_user: 'root' 
    root_password: 'secret'
    mysqld:
      bind-address: localhost
      log_error: /var/log/mariadb/mariadb.log
      pid-file: /var/run/mariadb/mariadb.pid
    mysqld_safe:
      bind-address: localhost
      log_error: /var/log/mariadb/mariadb.log
      pid-file: /var/run/mariadb/mariadb.pid
  database:
    - database
  schema:
    database:
      load: True
      source: salt://files/database.sql
  lookup:
    server: mariadb-server
    client: mariadb
    service: mariadb
  user:
    user:
      password: 'secret'
      host: localhost
      databases:
        - database: database
          grants: ['all privileges']
```

Master:
```
# salt --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Minion:
```
$ salt-call --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
