### ISSUE TITLE
Rendering SLS 'base:mysql.server' failed: while parsing a block mapping

### ISSUE THREAD

**Issue by NZI** [saltstack-formulas/mysql-formula#192]
Pillar data:

```yaml
mysql:
  server:
    root_password: 'password'
```

Salt:
```yaml
base:
  my-minion:
    - mysql
    - mysql.client
```

Error:

```
my-minion:
    Data failed to compile:
----------
    Rendering SLS 'base:mysql.server' failed: while parsing a block mapping
  in "<unicode string>", line 26, column 9:
            '{'root_password': 'password'}/s ...
            ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 26, column 12:
            '{'root_password': 'password'}/star ...
               ^
```
