### ISSUE TITLE
Two databases, two pillar files, one minion

### ISSUE THREAD

**Issue by grandmasterv** [saltstack-formulas/mysql-formula#219]
I tried to break out the pillar config per website we are hosting on a server and found that most formulas can handle it but not this one.  I would like to be able to define individual database level config per pillar file if possible.  Can anyone provide an example of defining two databases in separate pillar files that would work on a single minion with this formula?

As the formula currently stands, `site2.sls` config for the database overwrites `site1.sls` config.  The user configs however are properly merged and work.

### site1.sls
```
mysql:
  database:
    - name: site1
      character_set: utf8
  user:
    site1-user:
      password: site1-pass
      host: localhost
      databases:
        - database: site1          
          grants: ['select', 'insert', 'update', 'delete', 'create', 'alter','drop', 'index']
```

### site2.sls
```
mysql:
  database:
    - name: site2
      character_set: utf8
  user:
    site2-user:
      password: site2-pass
      host: localhost
      databases:
        - database: site2          
          grants: ['select', 'insert', 'update', 'delete', 'create', 'alter','drop', 'index']
```

### top.sls
```
'example-host':
    - site1.sls
    - site2.sls
```

I'm still new to modifying formulas but if someone could point me in a direction I can try my hand at an update to make the formula more flexible and support this.  I am worried though that this could be a big change to the functionality and would require everyone to update their pillar files so it may not be welcomed.
