### ISSUE TITLE
Can't use % in user:host

### ISSUE THREAD

**Issue by TaiSHiNet** [saltstack-formulas/mysql-formula#23]
Using latest develop branch. Tried %, '%', "%" and same variants with *

```
mysql_user_0:
  mysql_user.present:
    - name: redacted
    - host: %    <======================
    - password: 'redacted'

    - connection_host: localhost
    - connection_user: root
    - connection_pass: 'redacted'
```
