### ISSUE TITLE
[BUG] Arrays being dumped into config file in invalid form. 

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/mysql-formula#275]
### Versions reports (master & minion)

Salt: 3006.1+192.g23582dce20

### Pillar / config used

```
mysql:
  server_config:
    file: 50-server.cnf
    # my.cnf sections changes
    sections:
      mysqld:
        replicate-ignore-table:
          - core.table1
          - core.table2                 
          - core.table3    
``` 

---

### Describe the bug

When an array of data is inserted into the config file the above example is written out as

```
        replicate-ignore-table = ['core.table1',  'core.table2', 'core.table3']
```
This isn't a valid format for mysql configuration. 

### Expected behaviour

The output should be as follows. 
```
replicate-ignore-table                  = 'core.table1'
replicate-ignore-table                  = 'core.table2'
replicate-ignore-table                  = 'core.table3'
```

### Attempts to fix the bug

I've fixed it in a PR I'll be posting shortly.
