### ISSUE TITLE
Adapt for MariaDB

### ISSUE THREAD

**Issue by marshalls** [saltstack-formulas/mysql-formula#43]
It would be nice if you could adapt this to work with MariaDB - especially since CentOS/RedHat has dropped MySQL in favor of MariaDB.

**Comment by meatheadmike** [comment]
How did you install from the mysql community repo? It looks like package names are prefixed with mysql-community. So this formula still wont pick 'em up :(

**Comment by gravyboat** [comment]
@Cottser I believe the above comment is aimed at you.

**Comment by Cottser** [comment]
@meatheadmike who are you asking? I didn't mention the MySQL community repo, the comment above me did though. We may need more info from you to be able to help.

**Comment by meatheadmike** [comment]
This comment was aimed at @nmadhok. I'm on cent 7, so the formula currently does not work for me. He seemed to indicate that this could work with the community repo. But because of the naming convention used it does not. Sorry for the confusion guys.

**Comment by nmadhok** [comment]
@meatheadmike you're right that this formula won't pick the package names. We need to set the defaults for RHEL/Cent OS 7 in map.jinja. Could you submit a pull request for that?

**Comment by frnco** [comment]
@Cottser if you could please excuse my ignorance, I am completely new to SaltStack, but how should one proceed to use your sls files?

From what I gather, I could just drop them in my `/srv/salt` directory (As with Geoff's version seen in https://mariadb.com/blog/mariadb-devops-installing-mariadb-saltstack), but I want to also make sure the service is enabled. While editing your sls would probably work, I'm interested in the possibility of extending it (As you did with mysql), so I could have cleaner files. Is that desirable, or even possible? Or should I just edit it?

**Comment by Cottser** [comment]
@frnco you should use my sls files in conjunction with this formula, this formula already handles making sure the service is enabled. The files I provided are only useful when used in conjunction with this formula. Here's the documentation on setting up formulas: http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html

Once you have the formula in place you need to reference a copy of the mariadb.sls file from my gist from your topfile (top.sls) in your salt directory (in your case `/srv/salt`), and reference the pillar.sls (likely with a different name) from the topfile (top.sls) of your pillar directory, by default `/srv/pillar`.

So as a simple, bare-bones example, here's how the files would be set up:

/srv/salt/top.sls:

```
base:
  '*':
    - mysql
    - mysql.mariadb
```

/srv/salt/mysql/mariadb.sls - the contents of mariadb.sls from my gist.

/srv/pillar/top.sls:

```
base:
  '*':
    - mysql
```

/srv/pillar/mysql/init.sls - the contents of pillar.sls from my gist.

Hope that helps!

**Comment by ogabrielsantos** [comment]
[As of RHEL 7 default database are MariaDB](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.0_Release_Notes/chap-Red_Hat_Enterprise_Linux-7.0_Release_Notes-Web_Servers_and_Services.html#idp14278552).

You can use the follow workaround inside your `top.sls` pillar file.
````
mysql:
  lookup:
  {% if grains['os'] == 'CentOS' and grains['osmajorrelease'][0] == '7' %}
    server: mariadb-server
    client: mariadb
  {% endif %}
````

**Comment by litewhatever** [comment]
Can I overwrite configuration parameters also the same way as follows:
```
  lookup:
    server: mariadb-server
    client: mariadb
    service: mariadb
    python: MySQL-python
    server_config:
      sections:
        mysqld_safe:
          log_error: /var/log/mariadb/mariadb.log
          pid-file: /var/run/mariadb/mariadb.pid
```
Tried but dosn't seem to work. I'm new to salt :)

**Comment by vschum** [comment]
Try changing 'server_config' to 'config' and see if that works.

On Fri, Apr 29, 2016 at 3:42 AM, litewhatever <notifications@github.com>
wrote:

> Can I overwrite configuration parameters also the same way as follows:
>
>   lookup:
>     server: mariadb-server
>     client: mariadb
>     service: mariadb
>     python: MySQL-python
>     server_config:
>       sections:
>         mysqld_safe:
>           log_error: /var/log/mariadb/mariadb.log
>           pid-file: /var/run/mariadb/mariadb.pid
>
> Tried but dosn't seem to work. I'm new to salt :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack-formulas/mysql-formula/issues/43#issuecomment-215650412>
>



-- 
- Vincent Schumaker

**Comment by litewhatever** [comment]
@vschum nop, dosn't help. Actually I worked around it by defining if-endif as follows.

```
mysql:
  server:
    root_password: 'pass'
    {% if grains['os'] == 'CentOS' and grains['osmajorrelease'] == '7' %}
    mysqld_safe:
      log_error: /var/log/mariadb/mariadb.log
      pid_file: /var/run/mariadb/mariadb.pid
    {% endif %}
```
