### ISSUE TITLE
my.cnf sections do not permit multiple entries of same type

### ISSUE THREAD

**Issue by tedski** [saltstack-formulas/mysql-formula#67]
`my.cnf` requires some parameters to be specified multiple times.  An example would be `binlog-ignore-db`.  This formula cannot support that due to the `my.cnf` sections in the pillar being a dict.  

Using a list of dicts would solve this, but would break the current interface of the formula.  Any guidance on how to resolve this?

**Comment by thenewwazoo** [comment]
Oh, I think I get what you're saying:
```yaml
mysql:
  server:
    mysqld:
      - user: mysql
      - multiple-entry-item: trashdb1
      - multiple-entry-item: trashdb2
...
```

I think an easier way would be:
```yaml
mysql:
  server:
    mysqld:
      user: mysql
      multiple-entry-item:
        - trashdb1
        - trashdb2
```

I'm just not sure if there's a type test in jinja to distinguish between a bare value and a list.
