### ISSUE TITLE
Setting a "bind-address" pillar value doesn't restart MySQL

### ISSUE THREAD

**Issue by multani** [saltstack-formulas/mysql-formula#74]
If I set in my pillar something like this:
```
mysql:
  server:
    mysqld:
      bind-address: 0.0.0.0
```

... then the configuration file gets properly updated and the server gets reloaded but it's actually not sufficient and MySQL continues to listen on its default ``localhost`` address.
It has to be manually restarted for the change to take effect.

That would be cool if the formula takes care of this by itself.
